### ISSUE TITLE
[Add Book] Conflict fails to report right duplicate location

### ISSUE THREAD

**Issue by oscarngncc** [STommydx/2020S-COMP4111#32]
**Describe the bug**
When adding a duplicate book that has some info slightly changed, the "duplicate record" in book fails to report the right location of the book and returns -1 instead

**To Reproduce**
1. login accordingly.
2. insert a book.
3. insert a book with the same name in step 2, but has some property (e.g. year) adjusted.
4. Receive Conflict after request in step 3 accordingly
5. observe response header "duplicate record" to see the error 

**Expected behavior**
expected output in duplicate header: id of the first book in (2)
actual output in duplicate header: -1

**Screenshots**
According to this books table:
![image](https://user-images.githubusercontent.com/29769020/83406143-97cedc00-a440-11ea-8ec3-56665f32a1e6.png)

after making the duplicate request in step 3 and 4, the report returns Conflict accordingly. Notice that the year in this request body is slightly different (500 instead of 1200). The header at the bottom of picture returns -1 instead of 16
![image](https://user-images.githubusercontent.com/29769020/83406234-c9e03e00-a440-11ea-9531-4d6aa9289c3b.png)

**Comment by STommydx** [comment]
can be confirmed.

**Comment by STommydx** [comment]
opps
i forgot to change this when i modify the duplication criteria from the tuple (title, author, publisher, year) to title only. :disappointed: 
nice catch! :+1:
