### ISSUE TITLE
[Add Book] json body accepts null input

### ISSUE THREAD

**Issue by oscarngncc** [STommydx/2020S-COMP4111#34]
**Describe the bug**
"Year" in JSON body accepts null as an input. 

**To Reproduce**
1. Login Accordingly
2. Add Book with "Year": null as JSON body
3. Observe error

**Expected behavior**
expected output: 400 bad request
actual output: 201 Created with the book added ( year as 0 )

**Screenshots**
![image](https://user-images.githubusercontent.com/29769020/83407200-c6e64d00-a442-11ea-8611-49969f6eed13.png)

in database:
![image](https://user-images.githubusercontent.com/29769020/83407229-db2a4a00-a442-11ea-960d-49948b623638.png)

**Comment by STommydx** [comment]
The behavior is **intended**.
The behavior is not specified in the specification. It should be fine for any reasonable response that does not crash the server.
It is also a common practice to treat null values as zero for numeric types (like NULL is a constant value 0 in C++). So I think it is reasonable to implement it in this way.
IMO It should not be treated as a bug.

**Comment by oscarngncc** [comment]
I guess so, though that's implicit. On the other hand, I also found out that the JSON body accepts negative year input value. Is this also intended? Otherwise I can open it in another issue

**Comment by STommydx** [comment]
Yes, intended. I can imagine a book that is written before Christ lol.

**Comment by comp4111ta** [comment]
Technically, you set year = null. Thus, it does not violate the spec. However, in reality, it might be wired.
