### ISSUE TITLE
[Transaction] returns Success upon committing transaction with invalid action

### ISSUE THREAD

**Issue by oscarngncc** [STommydx/2020S-COMP4111#35]
**Describe the bug**
response returns Success upon committing transaction with invalid action

**To Reproduce**
1. Login Accordingly
2. Request for Transaction accordingly
3. Request an invalid action ( e.g. loan book with id=9000)
4. Commit the transaction
5. See error

(Alternative Way)
1. Login Accordingly
2. Request for Transaction accordingly
3. Request a valid action loaning a book
4. Commit the transaction accordingly
5. Request for Transaction again
6. Request an action again loaning the very same book in step 3 ( should be invalid)
7. Commit the transaction
8. See error

**Expected behavior**
Expected output: 400 Bad request
Actual output: 200 OK

**Screenshots**
![image](https://user-images.githubusercontent.com/29769020/83410705-74f4f580-a449-11ea-8fdc-6faf6edf9a9c.png)
![image](https://user-images.githubusercontent.com/29769020/83410741-8938f280-a449-11ea-8a95-8fec4e375e21.png)

**Comment by STommydx** [comment]
The behavior is intended.

According to the [canvas answer](https://canvas.ust.hk/courses/29927/discussion_topics/199516), we do not implement checking (book availability/existence) when adding an action. I implemented that behavior you described in phase 1 but it is not consistent with the description that the commit request corresponds to a MySQL transaction commit (which is given in FAQs/Phase 2 testcase).

The current way I am implementing it is such 'invalid' action (technically it is considered valid) is that it has no changes on the current book status. For commit, it will indeed do commit in the MySQL transaction. As there are no conflicts/database error for the transaction commit, the server would indeed return `200 OK`

I think there maybe cases that would cause commit error and I forgot to handle. However, this is not such cases.

**Comment by STommydx** [comment]
I'm marking this invalid for now. Please reopen the issue if appropriate.
Thanks you! :blush:
