### ISSUE TITLE
[Transaction] Fails to perform rollback upon invalid transaction

### ISSUE THREAD

**Issue by oscarngncc** [STommydx/2020S-COMP4111#36]
**Describe the bug**
Failure to perform rollback with invalid action within a transaction which has a series of actions.

**To Reproduce**
1. Login accordingly
2. request for transaction accordingly
3. PUT Request three actions in the order of ( valid -> invalid -> valid )
4. Commit the request
5. Observe the error

**Expected behavior**
expected:  400 bad request with rollback
actual: 200 OK with data written on the table

**Screenshots**
Suppose we have a table like this:
![擷取](https://user-images.githubusercontent.com/29769020/83411260-75da5700-a44a-11ea-9678-a73f5408c30a.PNG)

here, I have fired the following three requests, including:
1. Loan Book id of 3 (valid)
2. Loan Book id of 1 (invalid, since it's already loaned)
3. Loan Book id of 4 (valid)

Commit such transaction returns OK 200 instead of Bad request, also updates the table with book 3 and 4 being loaned instead of the whole transaction not getting executed, violating ACID according to specification:
![image](https://user-images.githubusercontent.com/29769020/83411403-bf2aa680-a44a-11ea-9d3c-ef55728ead7e.png)

**Comment by STommydx** [comment]
I did not rollback as I treated the actions are indeed committed successfully (described in #35). Could you give me a case that my server consider the commit is invalid but it did not rollback the changes? Or else I cannot count this as a separate bug.

**Comment by STommydx** [comment]
I will mark it as duplicate for the moment. Please reopen the issue if you found a case that my server consider the commit is invalid but it did not rollback the changes. Thanks.

**Comment by comp4111ta** [comment]
Undefined Behavior.
