### ISSUE TITLE
[Transaction] Automatic Timeout not working

### ISSUE THREAD

**Issue by oscarngncc** [STommydx/2020S-COMP4111#37]
**Describe the bug**
transaction doesn't cancel out automatically after a period of time according to the specification

**To Reproduce**
1. Login accordingly
2. Request transaction accordingly
3. Wait for more than 2 minutes 
4. Put an action and observe its response
5. Commit transaction and observe its response

**Expected behavior**
Expected: either in step 4 or step 5 it returns 400 bad request
Actual: 200 OK in both steps, also updating the table using the outdated transaction id

**Screenshots**
Original:
![擷取1](https://user-images.githubusercontent.com/29769020/83412420-a0c5aa80-a44c-11ea-814c-836d4ecc3248.PNG)

Request for Transaction ID:
![擷取](https://user-images.githubusercontent.com/29769020/83412483-b935c500-a44c-11ea-9627-25cd4e4a3475.PNG)

Wait for 5 minutes, and perform 'valid' (if it's not outdated) book return of id = 1
![擷取3](https://user-images.githubusercontent.com/29769020/83412492-bc30b580-a44c-11ea-9bf9-44722e6990a2.PNG)

Database get updated after commit:
![image](https://user-images.githubusercontent.com/29769020/83412525-cbaffe80-a44c-11ea-8a42-ab96a3a7bf74.png)

**Comment by STommydx** [comment]
There is indeed a timeout. It is the timeout limit of the MySQL connection. However, it is too long for one too see it in action.

**Comment by oscarngncc** [comment]
That's 8 hours by default! Which is different the requirement of about 2 minutes, sadly. However, specification refers it as "(e.g., there are no operations in 2 min)". So maybe that's fine? I can't prove it nor test it tho.

will let TA to decide 🔢

**Comment by STommydx** [comment]
the `e.g.` words suggests that 2 minutes is one of the many possible ways to implement the timeout. So I decided to leave it as the database default.

**Comment by comp4111ta** [comment]
The team passed deadlock check. Thus, not a bug for the timeout.
