### ISSUE TITLE
Receiving no responses for bad method requests

### ISSUE THREAD

**Issue by davidtang1006** [STommydx/2020S-COMP4111#38]
### Steps to reproduce the issue (1)

- Attempt to log in with `GET /BookManagementService/login` (it should be `POST`) and payload
  ```json
  {
      "Username": "user00001",
      "Password": "pass00001"
  }
  ```

### Steps to reproduce the issue (2)

1. Log in first.
2. Request a transaction ID.
3. Commit a transaction with `GET /BookManagementService/transaction?token=${token}` (it should be `POST`) and payload
   ```txt
   {
       "Transaction": ${transaction},
       "Operation": "commit"
   }
   ```

### Steps to reproduce the issue (3)

1. Log in first.
2. Add a book.
3. Request a transaction ID.
4. Attempt to loan the book with `GET BookManagementService/transaction?token=${token}` (it should be `PUT`) and payload
   ```txt
   {
       "Transaction": ${transaction},
       "Book": ${id},
       "Action": "loan"
   }
   ```

### What's the expected result?

Ideally `405 Method Not Allowed`.

### What's the actual result?

No responses are received.

**Comment by STommydx** [comment]
I cannot reproduce the issue.
From my testing, all of the three cases return `400 Bad Request`. 
Could you provide the some proofs that your cases indeed receive no response?
![Screenshot from 2020-06-02 20-27-01](https://user-images.githubusercontent.com/5105821/83520089-af28ca80-a50f-11ea-8291-9cabf9015453.png)
![Screenshot from 2020-06-02 20-28-09](https://user-images.githubusercontent.com/5105821/83520093-b059f780-a50f-11ea-849d-93685d6f6a96.png)
![Screenshot from 2020-06-02 20-28-28](https://user-images.githubusercontent.com/5105821/83520094-b0f28e00-a50f-11ea-981f-5fed0e62c2e3.png)

**Comment by davidtang1006** [comment]
I use JMeter to run the cases. [This](https://github.com/STommydx/2020S-COMP4111/files/4717599/custom-test-plan_bad-method-requests.zip) is the test plan. On my machine, I always receive no responses though.

<img width="884" alt="group2_issue_38_2_1" src="https://user-images.githubusercontent.com/43230869/83529407-e18cf480-a51c-11ea-9607-088f4b589aa2.png">
<img width="884" alt="group2_issue_38_2_2" src="https://user-images.githubusercontent.com/43230869/83529439-ec478980-a51c-11ea-8f8c-6771d77ad16a.png">

**Comment by STommydx** [comment]
I suspect the problem is from HTTPCore. It seems that HTTPCore assumes the body of a GET request is empty, and did not handle the entity content for GET requests correctly.

I have explicitly thrown `400 Bad Request` for method that is not equal to the intended method. You can check such behavior by using methods other than GET. This is not a bug from our side. Anyway, I appreciate your effort reporting such issue.

**Comment by STommydx** [comment]
Please let me know if you can reproduce this issue with other invalid methods other than `GET`. Feel free to reopen the issue if needed. Thank you.

**Comment by comp4111ta** [comment]
Cannot reproduce.
