### ISSUE TITLE
[/transaction] Failure to respond to some invalid requests

### ISSUE THREAD

**Issue by davidtang1006** [STommydx/2020S-COMP4111#39]
### Steps to reproduce the issue (1)

1. Log in first.
2. Request a transaction ID.
3. Request with `POST /BookManagementService/transaction?token=${token}` and payload
   ```txt
   {
       "Transaction": ${transaction},
       "Operation": null
   }
   ```
   (the operation should not be `null`).

### Steps to reproduce the issue (2)

1. Log in first.
2. Add a book.
3. Request a transaction ID.
4. Perform an action with `PUT /BookManagementService/transaction?token=${token}` and payload
   ```txt
   {
       "Transaction": ${transaction},
       "Book": ${id},
       "Action": null
   }
   ```
   (the action should not be `null`).

### What's the expected result?

`400 Bad Request`.

### What's the actual result?

No responses are received.

**Comment by STommydx** [comment]
Can confirm. 
I forgot null check in `TransactionAction` constructor and before the switch statement in `TransactionCommitRequestHandler`.
Nice catch!
